<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260912220631 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the transactions ledger table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE transactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, metal VARCHAR(16) NOT NULL, side VARCHAR(4) NOT NULL, quantity NUMERIC(18, 8) NOT NULL, price NUMERIC(18, 8) NOT NULL, currency VARCHAR(3) NOT NULL, idempotency_key VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_transactions_user_metal ON transactions (user_id, metal)');
        $this->addSql('CREATE INDEX idx_transactions_user_created_at ON transactions (user_id, created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_transactions_user_idempotency_key ON transactions (user_id, idempotency_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE transactions');
    }
}
